on: [ pull_request, workflow_dispatch]
name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ${{ vars.RUNNER_TEST }}
    env:
      GOPRIVATE: github.com/anyproto
    steps:
      - name: git config
        run: git config --global url.https://${{ secrets.ANYTYPE_PAT }}@github.com/.insteadOf https://github.com/

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        run: |
          echo GOPATH=$(go env GOPATH) >> $GITHUB_ENV
          echo GOBIN=$(go env GOPATH)/bin >> $GITHUB_ENV
          echo $(go env GOPATH)/bin >> $GITHUB_PATH
          make build-all
          cd go
          make test-full
